services:
  db:
      image: postgres:15-alpine
      container_name: todo_db
      restart: always
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=todo_list
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - "5433:5432"

  redis:
    image: redis:alpine
    container_name: todo_redis
    ports:
      - "6379:6379"
    restart: always

  backend:
    build: .
    command: python backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app  
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      - BOT_TOKEN=${BOT_TOKEN} 
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=todo_list
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432

  bot:
    build: .
    command: python bot/main.py
    volumes:
      - .:/app
    depends_on:
      - backend
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - API_BASE_URL=http://backend:8000/api/v1 
      - GEMINI_API_KEY=${GEMINI_API_KEY}

  celery:
    build: .
    command: celery -A config worker --beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - backend
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=config.settings
    working_dir: /app/backend 

volumes:
  postgres_data: